import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
=======
import { Toaster } from "sonner";
import Navbar from "@/components/navbar";
import { playfair, greatVibes } from "@/fonts";
>>>>>>> 846bba3e5d0918c2a48564a0bfbfd0ceeed28f13

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Beauty Channel",
  description: "Generated by MetaMAster",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body className="bg-black text-white">
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>

    </>
  );
}
